### ISSUE TITLE
Dynamic silencing fails

### ISSUE THREAD

**Issue by allcloud-jonathan** [terraform-providers/terraform-provider-datadog#138]
I'm trying to implement dynamic monitors that will automatically be muted for the next 5 minutes after a deployment.

### Terraform Version
```
$ terraform --version
Terraform v0.11.11
+ provider.datadog v1.6.0
+ provider.external v1.0.0

$ jq --version
jq-1.5
```

### Affected Resource(s)
- datadog_monitor

### Terraform Configuration Files
```hcl
data "external" "timestamp" {
  program = ["jq", "-rn", "now | floor | . + 300 | tostring | { timestamp: .  }"]
}

# Configure the Datadog provider by using the env variables DATADOG_API_KEY and DATADOG_APP_KEY
provider "datadog" {}

resource "datadog_monitor" "error_level" {
  name = "ErrorLevel"
  type = "metric alert"

  message = <<EOF_MESSAGE
  test
EOF_MESSAGE

  escalation_message = ""

  query = "avg(last_5m):avg:bot.error_level{} >= 2"

  thresholds {
    ok       = 0
    warning  = 1
    critical = 2
  }

  notify_no_data    = true
  no_data_timeframe = 10
  renotify_interval = 0

  notify_audit        = false
  timeout_h           = 0
  include_tags        = true
  require_full_window = false

  silenced {
    "*" = "${data.external.timestamp.result.timestamp}"
  }
}
```

### Debug Output
https://gist.github.com/allcloud-jonathan/ba4be20d42b54974ee89a341c4a21525

### Expected Behavior
Monitor silenced for the next 10 minutes

### Actual Behavior
`Error: datadog_monitor.error_level: silenced (*): cannot parse '' as int: strconv.ParseInt: parsing "${data.external.timestamp.result.timestamp}": invalid syntax`

### Steps to Reproduce
1. `terraform apply`

**Comment by bkabrda** [comment]
This seems to be a Terraform issue similar to other issue already reported. I added a note of this specific case in that issue to make sure it's covered: https://github.com/hashicorp/terraform/issues/19165#issuecomment-482143852

**Comment by allcloud-jonathan** [comment]
Hey @nmuesch,

no unfortunately not. We would actually like to really temporarily mute existing hosts during a terraform deployment. The developer (customer) is expected to monitor during the deployment and should not wake the on-call guy (college) in a different timezone.

**Comment by kmoe** [comment]
I've retested this with Terraform 0.12 (https://github.com/hashicorp/terraform/commit/dbcd9a56251d258e8735c3fc1237840ef29f8a22, `HEAD` of master as of now).

### Terraform version
```
$ terraform12 version
Terraform v0.12.4-dev
+ provider.datadog v2.0.2
+ provider.external v1.2.0
```

### Terraform Configuration Files

As above, with `terraform 0.12update` applied:

```
data "external" "timestamp" {
  program = ["jq", "-rn", "now | floor | . + 300 | tostring | { timestamp: .  }"]
}

# Configure the Datadog provider by using the env variables DATADOG_API_KEY and DATADOG_APP_KEY
provider "datadog" {
}

resource "datadog_monitor" "error_level" {
  name = "ErrorLevel"
  type = "metric alert"

  message = <<EOF_MESSAGE
  test
EOF_MESSAGE


  escalation_message = ""

  query = "avg(last_5m):avg:bot.error_level{} >= 2"

  thresholds = {
    ok = 0
    warning = 1
    critical = 2
  }

  notify_no_data = true
  no_data_timeframe = 10
  renotify_interval = 0

  notify_audit = false
  timeout_h = 0
  include_tags = true
  require_full_window = false

  silenced = {
    "*" = data.external.timestamp.result.timestamp
  }
}
```

### Behaviour
```
$ terraform12 plan
provider.datadog.api_key
  Enter a value: 

provider.datadog.app_key
  Enter a value: 


Warning: "silenced": [DEPRECATED] use Downtime Resource instead

  on example.tf line 52, in resource "datadog_monitor" "error_level":
  52: resource "datadog_monitor" "error_level" {



Error: Invalid function argument

  on example.tf line 2, in resource "local_file" "foo":
   2:   content  = cidrsubnet("10.0.0.0/8", 8, element(split(",", "k"), 1))

Invalid value for "netnum" parameter: a number is required.


Error: silenced (*): cannot parse '' as int: strconv.ParseInt: parsing "74D93920-ED26-11E3-AC10-0800200C9A66": invalid syntax

  on example.tf line 52, in resource "datadog_monitor" "error_level":
  52: resource "datadog_monitor" "error_level" {
```

### Analysis

As you can see, the error message in Terraform 0.12 is more descriptive, if a little esoteric. `"74D93920-ED26-11E3-AC10-0800200C9A66"` is an internal string Terraform uses for an unknown value.

It looks like there is a problem with Terraform Core here, although I don't believe it's the same one as raised in the initial bug report on https://github.com/hashicorp/terraform/issues/19165. I'm going to close https://github.com/hashicorp/terraform/issues/19165, so I would be very grateful if the maintainers of this provider would either:

1. Open a new issue in https://github.com/hashicorp/terraform using Terraform 0.12 and copying the reproduction steps from this issue, or
2. (Since `silenced` is now deprecated and soon to be removed), let me know that the interpolation problem no longer affects this provider, in which case I'll try to open an issue in https://github.com/hashicorp/terraform with a simpler reproduction case.

**Comment by nmuesch** [comment]
Hey @kmoe Thanks for the input on this one! You're right that we're moving away from the Silenced attribute in favor of the `downtime` resource. Would you be able to help open up an issue on Terraform core for this in that case?

I just tried this locally, using the dynamic data object for the downtime `start` field, and looks to work as expected. 

@allcloud-jonathan  Would using this dynamic setup in the downtime resource work for your use case? You can setup the downtime to apply for specific monitor tags, monitor ids, or just any scope tags, more information on this resource here - https://www.terraform.io/docs/providers/datadog/r/downtime.html

**Comment by nmuesch** [comment]
@allcloud-jonathan Hey, just wanted to check in and see if my last comment was able to help?

**Comment by allcloud-jonathan** [comment]
@nmuesch yes, this sounds like a possible solution. I've lacked the time to test it yet though, but I'll close for now
