### ISSUE TITLE
Query/Metric alert type change causing delete+recreate

### ISSUE THREAD

**Issue by platinummonkey** [terraform-providers/terraform-provider-datadog#241]
### Terraform Version
Seems after https://github.com/terraform-providers/terraform-provider-datadog/pull/236

### Affected Resource(s)
Please list the resources as a list, for example:
- monitor

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
N/A
define a standard `monitor` config for either `metric alert` type or `query alert` type but use the opposite type definition for the correct type. 

### Debug Output
This will delete the current monitor and create a new monitor.

### Panic Output
None

### Expected Behavior
update the monitor in place

### Actual Behavior
Deleted the monitor and created a new one.

### Steps to Reproduce
See above

### Important Factoids
Given that the API accepts either in this case and silently updates the type to the correct type. We should probably make an exception for https://github.com/terraform-providers/terraform-provider-datadog/pull/236 to disregard `metric/query alert` changes. 

### References
https://datadoghq.slack.com/archives/C3BM8SGKZ/p1561047720247900

**Comment by nmuesch** [comment]
Hey @platinummonkey Thanks for the issue report. Apologies for any inconvenience here. I was able to reproduce this with the following config:

```resource "datadog_monitor" "cpu_anomolous_test" {
  name = "Anomolous CPU usage"
  type = "query alert"
  message = "CPU utilization is outside normal bounds"
  query = "avg(last_4h):anomalies(ewma_20(avg:system.cpu.system{env:prod,service:website}.as_rate()), 'robust', 3, direction='below', alert_window='last_30m', interval=60, count_default_zero='true', seasonality='weekly') >= 1"
  thresholds {
    critical          = 1.0
    critical_recovery = 0.0
  }
  threshold_windows {
    trigger_window    = "last_30m"
    recovery_window   = "last_30m"
  }

  notify_no_data    = false
  renotify_interval = 60
}```

Seems like this issue is present only when you specify the monitor as a `query alert`, but Datadog views it as a `metric alert`. If you specify the monitor as a `metric alert` and the API returns a `query alert`, we hit this code path - https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_monitor.go#L383 that would cause the `type` change to be suppressed and `forceNew` not to be triggered. 

One approach forward would be to add to that `if` block, an `or` that adds the reverse. That way we also ignore the difference when the monitor type is specified as `query alert` but  the api returns a `metric alert` I believe this also gives us the benefit of 1) keeping the forceNew around for any other monitor type changes and 2) not recreating the monitors that were originally changed as part of this issue report. What do you think?

**Comment by platinummonkey** [comment]
I agree here, it should be compatible both directions.

**Comment by nmuesch** [comment]
We're aiming for a release in the morning with this!

**Comment by jgordor** [comment]
Hi @nmuesch I tried with 2.0.1 on old monitors defined as `type = "metric alert"` and still getting the type change:

```
type:                         "query alert" => "metric alert" (forces new resource)
```

The fix is only for newly created monitors? or should work also for existing ones?

Thanks

**Comment by nmuesch** [comment]
Hey @jgordor Apologies for any inconvenience here. We've been looking into another report of this as well and so far it appears to only impact existing monitors (not the creation/update of new monitors)

It looks like the state contains the other monitor type `query alert` despite the config having `metric alert` Newly created monitors should leave the state with `metric alert` and not have this diff. We're still investigating though, I just wanted to share where we are currently. I'll update here again with any new information. 

Going to re open this issue, thanks for the report!

**Comment by jgordor** [comment]
Thanks, tested and is working!
