### ISSUE TITLE
Support for 'process alert' monitors

### ISSUE THREAD

**Issue by Caledonia91** [terraform-providers/terraform-provider-datadog#258]
Currently the terraform provider does not support monitors with the type `process alert`.

Is it planned to add this functionality into a later release?

**Comment by nmuesch** [comment]
Hey @Caledonia91 Thanks for the issue report and apologies for the delay. The latest version of the Datadog Terraform Provider should support Process Alert Monitors. We've merged in a PR to share what an example config would look like https://github.com/terraform-providers/terraform-provider-datadog/pull/273/files

I'll go ahead and close this issue for now but please do let me know if you continue to experience an issue with this.

**Comment by andyjp94** [comment]
@nmuesch the link to that PR is broken unfortunately and the terraform provider does not say that it supports monitors with `process alert`. Could you please confirm if this is the case or not?

**Comment by nmuesch** [comment]
Hey @andyjp94, unfortunately any old PR/issue links need to replace `hashicorp` with `DataDog` in order to work since the repository was migrated to the DataDog github organization. You can find the original PR here - https://github.com/DataDog/terraform-provider-datadog/pull/273

Process Alert monitors are supported in this provider, here's an example of setting one up https://registry.terraform.io/providers/DataDog/datadog/latest/docs/guides/monitors#process-monitors
