### ISSUE TITLE
Feature request: support for pagerduty integrations

### ISSUE THREAD

**Issue by mblakele** [terraform-providers/terraform-provider-datadog#75]
Wiring datadog and pagerduty together can be somewhat tedious: I wish terraform could help.

It looks like @rlhh has done some work at https://github.com/terraform-providers/terraform-provider-datadog/pull/54 but I'm not sure how mature it is.

Docs: https://docs.datadoghq.com/api/?lang=bash#pagerduty

**Comment by snemetz** [comment]
Since the Datadog APIs for integration want the full config at once instead of being able to add/remove 1 service at a time, there is a problem using Terraform if you manage each service independently (microservices). In AWS, I'm using a combination of Terraform, S3, and Lambdas to automate this and achieve independent service management

**Comment by snemetz** [comment]
It's just ready to go live. Could use some improvements, but it is working
https://github.com/devops-workflow/terraform-aws-datadog-integrations

**Comment by taiidani** [comment]
Was this closed by #135? Asking for a friend...who is going to attempt to set it up in a microservices-style configuration.

**Comment by bkabrda** [comment]
I've just submitted https://github.com/terraform-providers/terraform-provider-datadog/pull/237 which utilizes new DD API endpoints to solve this in a better way, feel free to review!

**Comment by bkabrda** [comment]
Implemented in #237 which was just merged. Closing this issue.
