### ISSUE TITLE
Import does not honour defaults, and causes an import+plan to make changes

### ISSUE THREAD

**Issue by nickatsegment** [terraform-providers/terraform-provider-datadog#94]
When importing Datadog monitors, certain fields (namely `include_tags`) may be missing. These get written not using the default in the schema, but the Go zero value, which may be different.

For example, say the Datadog monitor API returns this JSON (viz, `include_tags` is missing):

```json
{
...
"options": {}
}
```

This gets written as `include_tags = false` even though the default is `true`.

```bash
$ terraform state show datadog_monitor.12345
id                  = 12345
...
include_tags        = false
...
```

If I then try to `terraform plan` with 
```
"resource" "datadog_monitor" "12345" {
...
  "include_tags" = true
}
```

I will see a change:
```bash
$ terraform plan -target datadog_monitor.12345
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

datadog_monitor.12345: Refreshing state... (ID: 12345)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ datadog_monitor.12345
      include_tags: "false" => "true"
```

If applied, this writes the new explicit value to Datadog.

I wrote a test that shows this happening (it's rough): https://github.com/terraform-providers/terraform-provider-datadog/commit/496908e41d9d5b1b9bd993c5de21bb9dbfec6eb5

And a (rough) fix: https://github.com/terraform-providers/terraform-provider-datadog/commit/357222fd87636174ae1a12a8e45e64f9a17e3d74

### Terraform Version

```
Terraform v0.11.8
+ provider.datadog v1.2.0
```

### Affected Resource(s)

- datadog_monitor

**Comment by bkabrda** [comment]
So this really seems to be an issue of the Datadog API, since it should return full specs of requested entities. I'll see what I can do about making this fixed systematically on the API side, but in the meanwhile I think the proposed fix looks good. @nickatsegment do you want to submit this as a PR?

**Comment by nmuesch** [comment]
Hey @nickatsegment Sorry for the delay here. This `includes_tag` field was actually added to the `monitor get` api response with the default being True. This should be reflected on any new monitor and any monitor that gets updated without this field being explicitly set. 

Thanks for your helpful issue details and original PR. I'll go ahead and close this issue since this should be resolved going forward. (On any existing monitors, the first `terraform apply` should let this include_tags value be properly reflected in the state) Please do let me know if you continue to experience this issue!
